global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-prototepe9.2sem.students-projects.ru
    path: /
    pathType: Prefix
  containerPort: 80
  image: baranovr605/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "400m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql-service:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
    mongoUri: "mongodb://user:password@mongodb:27017/reportdtdb?authSource=reportdtdb"
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
  image: baranovr605/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "400m"
  containerPort: 8080
  livenessProbe:
    httpGet:
        path: "/actuator/health"
        port: 8080
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5
  vpa:
    updatePolicy:
      updateMode: "Recreate"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "100m"
            memory: "128Mi"
          maxAllowed:
            cpu: "400m"
            memory: "256Mi"
          controlledResources: ["cpu", "memory"]
          controlledValues: RequestsAndLimits

backend-report:
  port: "8080"
  containerPort: "8080"
  mongoConnectStringBase64: "mongodb://user:password@mongodb:27017/reportdtdb"
  revisionHistoryLimit: 15
  replicaCount: 1
  strategy:
    type: Recreate
  image: baranovr605/sausage-backend-report:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "400m"
  hpaCPUUtilization: 60
  hpaMemoryUtilization: 60

infra:
  postgresql:
    replicas: 1
    image: postgres:16-alpine
    storage: "1Gi"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "400m"
    env:
      POSTGRES_PASSWORD: storepassword
      POSTGRES_USER: store
      POSTGRES_DB: sausage-store
    network:
      protocol: "TCP"
      port: 5432

  
  mongodb:
    image: "mongo:7.0"
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    storage: "512Mi"
    env:
      MONGO_INITDB_DATABASE: "reportdtdb"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
    user:
      name: "user"
      password: "password"
    containerPort: 27017
    mongodbInit:
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "200m"
