-- Create Table product
CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  picture_url VARCHAR(255)
);

-- Create Table product_info
CREATE TABLE product_info (
  product_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DOUBLE PRECISION
);

-- Create Table orders
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  status VARCHAR(255)
);

-- Create Table orders_date
CREATE TABLE orders_date (
  order_id BIGINT NOT NULL,
  status VARCHAR(255),
  date_created DATE DEFAULT CURRENT_DATE
);

-- Create Table order_product
CREATE TABLE order_product (
  quantity INTEGER NOT NULL,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL
);
